### ISSUE TITLE
feat(ui): make landing page

### ISSUE THREAD

**Issue by Archiruz** [GDSC-UM-Indonesia/nextjs_finalproject#3]
## Konteks
Mengembangkan laman utama / beranda dari website. Terdapat beberapa komponen utama pada laman ini, yakni:

1. Hero Section, bagian laman awal yang memberikan penjelasan singkat tentang GDSC dan logo
2. Daftar Artikel, bagian yang menampilkan artikel - artikel yang telah dirilis, berurutan berdasarkan tanggal rilis.
3. Footer, halaman terakhir yang menampilkan sitemap sederhana website

## Epics / Sub Task List

- [x] #17
- [x] #16
- [x] #18
- [x] #15

## Design Spec

Please look it up at [Figma Workfile](https://www.figma.com/file/hkp1AvFFaz1Y64FTLu3ldb/WEB-GDSC-UM?type=design&node-id=1-2)

**HERO SECTION**
![image](https://github.com/GDSC-UM-Indonesia/nextjs_finalproject/assets/14950309/7c4fa0f8-2033-45c2-b492-29eb37672c46)

**ARTICLE LIST**
![image](https://github.com/GDSC-UM-Indonesia/nextjs_finalproject/assets/14950309/f085ba3a-eee5-4e14-8c59-1eb5b058f738)

**FOOTER SECTION**
![image](https://github.com/GDSC-UM-Indonesia/nextjs_finalproject/assets/14950309/52d5d07c-183a-48e9-baa3-b761e91aad1b)

**Comment by vzrenggamani** [comment]
Done in #34 and #33
