### ISSUE TITLE
feat(ui): make profile page

### ISSUE THREAD

**Issue by Archiruz** [GDSC-UM-Indonesia/nextjs_finalproject#4]
## Konteks
Develop pages that show the GDSC UM Team and its members, it should be showing atleast
- Name
- Photo Profile
- Social Media (LinkedIn/Instagram)
- Public Email Address
- Roles in GDSC

## Technical Implementation
We could use something like JSON File to populate the members data like this structure:
```json
[
  {
    "id": "uuid",
    "nama": "nama",
    "role": "role",
    "email": "gdsc@um.acid",
    "socialmedia": [
      "https://instagram.com/gdsc",
      "https://linkedin.com/gdsc"
    ]
  }
]
```
**OR** we could populate them using Google Spreadsheet data like we are using in Quiz System
| id | nama | role | email | sosial media |
| -- | -- | -- | -- | -- |
| uuid | nama | lead | gdsc@um.ac.id | linkedin.gdsc |

## Design Implementation

Waiting from the team UI

**Comment by vzrenggamani** [comment]
Done in #34
